/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * plotPanel.java
 *
 * Created on Nov 30, 2010, 11:39:37 PM
 */

package eGraph;

import java.awt.event.ActionEvent;

/**
 * This Object gets added to a JTabbedPane
 * 
 */
public class SlopeInterceptDemoPanel extends javax.swing.JPanel {

    /** Creates new form plotPanel */
    public SlopeInterceptDemoPanel() {
        initComponents();
        xInvertBox.setVisible(false);
        yInvertBox.setVisible(false);
        yInterceptInvertBox.setVisible(false);
        xCheckBox.setVisible(false);
        yCheckBox.setVisible(false);
        yInterceptCheckBox.setVisible(false);
        jSplitPane1.setOneTouchExpandable(true);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jToolBar3 = new javax.swing.JToolBar();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        yCheckBox = new javax.swing.JCheckBox();
        xCheckBox = new javax.swing.JCheckBox();
        yInterceptCheckBox = new javax.swing.JCheckBox();
        yInterceptSpinner = new javax.swing.JSpinner();
        ySpinner = new javax.swing.JSpinner();
        xSpinner = new javax.swing.JSpinner();
        upButton = new javax.swing.JButton();
        downButton = new javax.swing.JButton();
        yInvertBox = new javax.swing.JCheckBox();
        xInvertBox = new javax.swing.JCheckBox();
        yInterceptInvertBox = new javax.swing.JCheckBox();
        jToolBar2 = new javax.swing.JToolBar();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        quadrantSpinner = new javax.swing.JSpinner();
        numbersBox = new javax.swing.JCheckBox();
        ghostCheckBox = new javax.swing.JCheckBox();
        jToolBar1 = new javax.swing.JToolBar();
        refreshButton = new javax.swing.JButton();
        lineBox = new javax.swing.JCheckBox();
        pointsBox = new javax.swing.JCheckBox();
        paperPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jSplitPane1.setDividerSize(14);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSplitPane1MouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jToolBar3.setRollover(true);
        jToolBar3.setPreferredSize(new java.awt.Dimension(350, 140));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(330, 160));
        jPanel2.setPreferredSize(new java.awt.Dimension(330, 160));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/x.plus.png"))); // NOI18N
        jLabel1.setToolTipText("y=mx+b");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, 40));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 68, 60, 10));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/y.equals.png"))); // NOI18N
        jLabel2.setToolTipText("y=mx+b");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 60, 40));

        yCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        yCheckBox.setToolTipText("Include numerator in change");
        jPanel2.add(yCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 40, 20));

        xCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        xCheckBox.setToolTipText("Include denominator in change");
        jPanel2.add(xCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 40, 20));

        yInterceptCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        yInterceptCheckBox.setToolTipText("Include y-intercept in change");
        jPanel2.add(yInterceptCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 20, 20));

        yInterceptSpinner.setFont(new java.awt.Font("Tahoma", 1, 18));
        yInterceptSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(2), null, null, Integer.valueOf(1)));
        yInterceptSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                yInterceptSpinnerStateChanged(evt);
            }
        });
        jPanel2.add(yInterceptSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 60, 40));

        ySpinner.setFont(new java.awt.Font("Tahoma", 1, 18));
        ySpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(3), null, null, Integer.valueOf(1)));
        ySpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ySpinnerStateChanged(evt);
            }
        });
        jPanel2.add(ySpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 60, 40));

        xSpinner.setFont(new java.awt.Font("Tahoma", 1, 18));
        xSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(2), null, null, Integer.valueOf(1)));
        xSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                xSpinnerStateChanged(evt);
            }
        });
        jPanel2.add(xSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 60, 40));

        upButton.setFont(new java.awt.Font("Tahoma", 1, 14));
        upButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/sort-up.png"))); // NOI18N
        upButton.setToolTipText("Hold CTRL or ALT and click this button for more options.");
        upButton.setMargin(new java.awt.Insets(2, 4, 2, 4));
        upButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upButtonActionPerformed(evt);
            }
        });
        jPanel2.add(upButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 40, 40));

        downButton.setFont(new java.awt.Font("Tahoma", 1, 14));
        downButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/sort-down.png"))); // NOI18N
        downButton.setToolTipText("Hold CTRL or ALT and click this button for more options.");
        downButton.setMargin(new java.awt.Insets(2, 4, 2, 4));
        downButton.setPreferredSize(new java.awt.Dimension(25, 27));
        downButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downButtonActionPerformed(evt);
            }
        });
        jPanel2.add(downButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 40, 40));

        yInvertBox.setBackground(new java.awt.Color(0, 51, 51));
        yInvertBox.setToolTipText("Invert change rate");
        jPanel2.add(yInvertBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 21, 20, 20));

        xInvertBox.setBackground(new java.awt.Color(0, 51, 51));
        xInvertBox.setToolTipText("Invert change rate");
        jPanel2.add(xInvertBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 99, -1, -1));

        yInterceptInvertBox.setBackground(new java.awt.Color(0, 51, 51));
        yInterceptInvertBox.setToolTipText("Invert change rate");
        jPanel2.add(yInterceptInvertBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));

        jToolBar3.add(jPanel2);

        jPanel1.add(jToolBar3);

        jToolBar2.setRollover(true);
        jToolBar2.setMinimumSize(new java.awt.Dimension(310, 140));
        jToolBar2.setPreferredSize(new java.awt.Dimension(320, 140));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setMinimumSize(new java.awt.Dimension(250, 145));

        jLabel3.setText("Quadrant Range");

        quadrantSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(8), null, null, Integer.valueOf(1)));

        numbersBox.setSelected(true);
        numbersBox.setText("Show Numbers");
        numbersBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numbersBoxActionPerformed(evt);
            }
        });

        ghostCheckBox.setSelected(true);
        ghostCheckBox.setText("Show Ghost Points");
        ghostCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ghostCheckBoxActionPerformed(evt);
            }
        });

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        refreshButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/synchronized.png"))); // NOI18N
        refreshButton.setToolTipText("Manual Refresh");
        refreshButton.setMargin(new java.awt.Insets(2, 4, 2, 4));
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(refreshButton);

        lineBox.setSelected(true);
        lineBox.setText("Show Line");
        lineBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lineBoxActionPerformed(evt);
            }
        });

        pointsBox.setSelected(true);
        pointsBox.setText("Show Points");
        pointsBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pointsBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ghostCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(quadrantSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                            .addComponent(lineBox, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pointsBox, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(numbersBox, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quadrantSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numbersBox)
                    .addComponent(lineBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ghostCheckBox)
                    .addComponent(pointsBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jToolBar2.add(jPanel3);

        jPanel1.add(jToolBar2);

        jSplitPane1.setLeftComponent(jPanel1);

        paperPanel.setLayout(new java.awt.BorderLayout());
        jSplitPane1.setRightComponent(paperPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void upButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upButtonActionPerformed
        int mod = evt.getModifiers();
        if ((mod & ActionEvent.ALT_MASK) == ActionEvent.ALT_MASK){
            boolean setting = true;
            if (xInvertBox.isVisible()) {
                    setting = false;
                }
            xInvertBox.setVisible(setting);
            yInvertBox.setVisible(setting);
            yInterceptInvertBox.setVisible(setting);
            return;
        }
        if ((mod & ActionEvent.CTRL_MASK) == ActionEvent.CTRL_MASK){
            boolean setting = true;
            if (xCheckBox.isVisible()) {
                    setting = false;
                    xCheckBox.setSelected(setting);
                    xCheckBox.setSelected(setting);
                    yInterceptCheckBox.setSelected(setting);
                }
            xCheckBox.setVisible(setting);
            yCheckBox.setVisible(setting);
            yInterceptCheckBox.setVisible(setting);
            return;
        }
        up();
    }//GEN-LAST:event_upButtonActionPerformed

    private void downButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downButtonActionPerformed
        int mod = evt.getModifiers();
        if ((mod & ActionEvent.ALT_MASK) == ActionEvent.ALT_MASK){
            boolean setting = true;
            if (xInvertBox.isVisible()) {
                    setting = false;
                    /* unselect the boxes when hiding them */
                    xInvertBox.setSelected(setting);
                    yInvertBox.setSelected(setting);
                    yInterceptInvertBox.setSelected(setting);
                }
            xInvertBox.setVisible(setting);

            yInvertBox.setVisible(setting);
            yInterceptInvertBox.setVisible(setting);
            return;
        }
        if ((mod & ActionEvent.CTRL_MASK) == ActionEvent.CTRL_MASK){
            boolean setting = true;
            if (xCheckBox.isVisible()) {
                    setting = false;
                    /* unselect the boxes when hiding them */
                    xCheckBox.setSelected(setting);
                    xCheckBox.setSelected(setting);
                    yInterceptCheckBox.setSelected(setting);
                }
            xCheckBox.setVisible(setting);
            yCheckBox.setVisible(setting);
            yInterceptCheckBox.setVisible(setting);
            return;
        }
        down();
    }//GEN-LAST:event_downButtonActionPerformed

    private void numbersBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numbersBoxActionPerformed
        buildGraph();
    }//GEN-LAST:event_numbersBoxActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        
        buildGraph();
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void ySpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ySpinnerStateChanged
        buildGraph();
    }//GEN-LAST:event_ySpinnerStateChanged

    private void xSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_xSpinnerStateChanged
        buildGraph();
    }//GEN-LAST:event_xSpinnerStateChanged

    private void yInterceptSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_yInterceptSpinnerStateChanged
        buildGraph();
    }//GEN-LAST:event_yInterceptSpinnerStateChanged

    private void ghostCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ghostCheckBoxActionPerformed
        buildGraph();
    }//GEN-LAST:event_ghostCheckBoxActionPerformed

    private void lineBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lineBoxActionPerformed
        buildGraph();
    }//GEN-LAST:event_lineBoxActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
       
    }//GEN-LAST:event_formKeyPressed

    private void pointsBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pointsBoxActionPerformed
        buildGraph();
    }//GEN-LAST:event_pointsBoxActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        
    }//GEN-LAST:event_formFocusGained

    private void jSplitPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSplitPane1MouseClicked
       
    }//GEN-LAST:event_jSplitPane1MouseClicked
    

    private void up(){
        int temp = 0;
        if (yInterceptCheckBox.isSelected()){
            temp = (Integer)yInterceptSpinner.getValue();
            if (yInterceptInvertBox.isSelected()){
                temp--;
            }else temp++;

            yInterceptSpinner.setValue(temp);
        }
        if (xCheckBox.isSelected()){
            temp = (Integer)xSpinner.getValue();
            if (xInvertBox.isSelected()){
                temp--;
            }else temp++;
            xSpinner.setValue(temp);
        }
        if (yCheckBox.isSelected()){
            temp = (Integer)ySpinner.getValue();
            if (yInvertBox.isSelected()){
                temp--;
            }else temp++;

            ySpinner.setValue(temp);
        }
        this.buildGraph();
    }
    private void down(){
        int temp = 0;

        if (yInterceptCheckBox.isSelected()){
            temp = (Integer)yInterceptSpinner.getValue();
            if (yInterceptInvertBox.isSelected()){
                temp++;
            }else temp--;
            yInterceptSpinner.setValue(temp);
        }
        if (xCheckBox.isSelected()){
            temp = (Integer)xSpinner.getValue();
            if (xInvertBox.isSelected()){
                temp++;
            }else temp--;
            xSpinner.setValue(temp);
        }
        if (yCheckBox.isSelected()){
            temp = (Integer)ySpinner.getValue();
            if (yInvertBox.isSelected()){
                temp++;
            }else temp--;
            ySpinner.setValue(temp);
        }
        this.buildGraph();
    }

    public void buildGraph(){
        paperPanel.removeAll(); //I was stacking a new slopeCanvas in each htime the demo was updated, needless to say the tabbedpane got real heavy
        int q = (Integer)quadrantSpinner.getValue();
        int x = (Integer)xSpinner.getValue();
        int y = (Integer)ySpinner.getValue();
        int yi = (Integer)yInterceptSpinner.getValue();

        /* y over x */
        /* Keep our slope "fraction" under control */
        
            if (y < 0 && x < 0) {
                y = y * -1;
                x = x * -1;                
            }//currently have a small issue with the algorithm when 0 over 0 is crossed

            xSpinner.setValue(x);
            ySpinner.setValue(y);
                
        paperPanel.add(new SlopeCanvas(q, numbersBox.isSelected(), ghostCheckBox.isSelected(),
                         lineBox.isSelected(), pointsBox.isSelected(), paperPanel.getSize(), x, y, yi));
        this.validate();
        
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton downButton;
    private javax.swing.JCheckBox ghostCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JCheckBox lineBox;
    private javax.swing.JCheckBox numbersBox;
    private javax.swing.JPanel paperPanel;
    private javax.swing.JCheckBox pointsBox;
    private javax.swing.JSpinner quadrantSpinner;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton upButton;
    private javax.swing.JCheckBox xCheckBox;
    private javax.swing.JCheckBox xInvertBox;
    private javax.swing.JSpinner xSpinner;
    private javax.swing.JCheckBox yCheckBox;
    private javax.swing.JCheckBox yInterceptCheckBox;
    private javax.swing.JCheckBox yInterceptInvertBox;
    private javax.swing.JSpinner yInterceptSpinner;
    private javax.swing.JCheckBox yInvertBox;
    private javax.swing.JSpinner ySpinner;
    // End of variables declaration//GEN-END:variables

}
